version: "2"
services:
  web:
    container_name: swag
    restart: always
    # replace username/repo:tag with your name and image details
    image: niwde/server-php7.1
    volumes:
        - "./shared/scripts:/home/webshop/scripts"
        - "./shared/web:/var/www/html"
        - "./shared/logs/apache:/var/log/apach2"
    environment:
        - SWAG_BRANCH=labs
        - SWAG_VERSION=last
        - SWAG_USER=demo
        - SWAG_PASS=demo
    ports:
        - "30022:22"
        - "30080:80"
        - "39000:9000"
    #networks:
      #- webnet
  db:
    container_name: swag_db
    restart: always
    image: mysql:5.7
    volumes:
        - "./shared/db:/var/lib/mysql"
        - "./shared/logs/mysql:/var/log/mysql"
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=shopware
        - MYSQL_USER=webshop
        - MYSQL_PASSWORD=webshop
    ports:
      - "33306:3306"
    #networks:
      #- webnet
#networks:
  #webnet:
    #driver: bridge
